package dev.aas.android.protocol

import kotlinx.serialization.KSerializer
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * Every golden fixture generated by `cargo test -p aas-protocol` decodes into the Kotlin
 * models and re-encodes to semantically equal JSON. A mismatch means the Rust and Kotlin
 * definitions of the protocol drifted apart.
 *
 * Coverage is checked both ways: the tree holds only the known category folders with JSON
 * files directly inside (each category test reads every file of its folder), and every method,
 * event type, notification, error kind and HTTP body the client knows has a fixture.
 */
class FixturesTest {
    private fun files(dir: String): List<File> {
        val d = File(root, dir)
        assertTrue(d.isDirectory, "missing fixture directory $d")
        val all = d.listFiles()!!.sortedBy { it.name }
        val strays = all.filter { !it.isFile || it.extension != "json" }
        assertTrue(strays.isEmpty(), "unexpected entries in $d: ${strays.map { it.name }}")
        assertTrue(all.isNotEmpty(), "no fixtures in $d")
        return all
    }

    private fun read(file: File): JsonElement = AasJson.parseToJsonElement(file.readText())

    private fun <T> roundTrip(serializer: KSerializer<T>, element: JsonElement, where: String): T {
        val decoded = try {
            AasJson.decodeFromJsonElement(serializer, element)
        } catch (e: Exception) {
            fail("$where: decode failed: ${e.message}")
        }
        val encoded = AasJson.encodeToJsonElement(serializer, decoded)
        assertEquals(element, encoded, "$where: re-encoded JSON differs")
        return decoded
    }

    private fun methodName(file: File): String = file.nameWithoutExtension.replaceFirst('_', '/')

    /**
     * A request fixture is named `<method>.json`, or `<method>_<variant>.json` for another shape
     * of the method's params (`aas_protocol::examples::request_variants`). Method names have one
     * `/` and no `_`.
     */
    private fun requestMethodName(file: File): String = file.nameWithoutExtension.split('_', limit = 3).take(2).joinToString("/")

    private fun isRequestVariant(file: File): Boolean = file.nameWithoutExtension.split('_', limit = 3).size == 3

    @Test
    fun theFixtureTreeHasExactlyTheKnownCategories() {
        val dirs = root.listFiles()!!.map { it.name }.toSet()
        assertEquals(CATEGORIES, dirs, "fixture categories under $root")
        assertTrue(root.listFiles()!!.all { it.isDirectory }, "only category folders at the top level")
    }

    @Test
    fun requests() {
        val names = mutableSetOf<String>()
        val variants = mutableSetOf<String>()
        for (file in files("requests")) {
            val msg = roundTrip(RpcMessage.serializer(), read(file), file.name)
            assertEquals(RpcMessage.Kind.Request, msg.kind, file.name)
            val method = assertNotNull(Methods.byName(msg.method!!), "${file.name}: unknown method ${msg.method}")
            assertEquals(requestMethodName(file), method.name, file.name)
            if (isRequestVariant(file)) variants += file.name
            roundTrip(method.params, msg.params!!, "${file.name} params")
            if (method.mutating) {
                assertTrue((msg.params as JsonObject).containsKey("clientRequestId"), "${file.name}: mutating without clientRequestId")
            } else {
                assertTrue((msg.params as? JsonObject)?.containsKey("clientRequestId") != true, "${file.name}: read-only with clientRequestId")
            }
            names += method.name
        }
        assertEquals(Methods.all.map { it.name }.toSet(), names, "every method has a request fixture")
        assertEquals(REQUEST_VARIANTS, variants, "the request variants, each checked by a test of its own below")
    }

    /**
     * `thread/create` in another thread's workspace (protocol.md §4): what 「新しいスレッドで実装」
     * sends for a plan of a worktree thread. The daemon's fixture decodes into the shape the app
     * builds, and the app writes it back the same way.
     */
    @Test
    fun aThreadIsCreatedInAnotherThreadsWorkspace() {
        val file = File(root, "requests/thread_create_workspaceThread.json")
        val msg = AasJson.decodeFromJsonElement(RpcMessage.serializer(), read(file))
        val params = roundTrip(Methods.ThreadCreate.params, msg.params!!, file.name)
        assertEquals(WorkspaceSpec.Thread("thr_01K6A0000000000000000THR02"), params.workspace)
        assertEquals(
            AasJson.parseToJsonElement("""{"kind":"thread","threadId":"thr_01K6A0000000000000000THR02"}"""),
            (msg.params as JsonObject)["workspace"],
        )
    }

    @Test
    fun responses() {
        val names = mutableSetOf<String>()
        for (file in files("responses")) {
            val msg = roundTrip(RpcMessage.serializer(), read(file), file.name)
            assertEquals(RpcMessage.Kind.Response, msg.kind, file.name)
            val method = assertNotNull(Methods.byName(methodName(file)), "${file.name}: unknown method")
            roundTrip(method.result, msg.result!!, "${file.name} result")
            names += method.name
        }
        assertEquals(Methods.all.map { it.name }.toSet(), names, "every method has a response fixture")
    }

    @Test
    fun events() {
        val types = mutableSetOf<String>()
        for (file in files("events")) {
            val envelope = roundTrip(EventEnvelope.serializer(), read(file), file.name)
            val type = assertNotNull(Event.typeOf(envelope.event), "${file.name}: decoded as an unknown event")
            types += type
            if (file.name.endsWith("_coalesced.json")) assertNotNull(envelope.seqFrom, file.name)
        }
        assertEquals(Event.knownTypes.toSet(), types, "every event type has a fixture")
        assertEquals(Event.knownTypes.size, Event.knownTypes.toSet().size, "event types are unique")
        for (type in Event.knownTypes) assertNotNull(Event.serializerFor(type), "no serializer for $type")
    }

    @Test
    fun notifications() {
        val methods = mutableSetOf<String>()
        for (file in files("notifications")) {
            val msg = roundTrip(RpcMessage.serializer(), read(file), file.name)
            assertEquals(RpcMessage.Kind.Notification, msg.kind, file.name)
            val parsed = ServerNotification.parse(msg.method!!, msg.params)
            assertTrue(parsed !is ServerNotification.Unknown, "${file.name}: unknown notification")
            assertEquals(msg.params, ServerNotification.paramsOf(parsed), "${file.name}: params differ")
            methods += msg.method
        }
        assertEquals(ServerNotification.knownMethods.toSet(), methods, "every notification has a fixture")
    }

    @Test
    fun errors() {
        val kinds = mutableSetOf<ErrorKind>()
        for (file in files("errors")) {
            val msg = roundTrip(RpcMessage.serializer(), read(file), file.name)
            val error = assertNotNull(msg.error, file.name)
            assertEquals(file.nameWithoutExtension, error.kind.wire, file.name)
            assertEquals(error.kind.code, error.code, file.name)
            // Every `data` field the client reads is typed; the fixture carries each one it has.
            val data = error.data as? JsonObject
            for ((key, read) in ERROR_DETAILS) {
                if (data?.containsKey(key) == true) assertNotNull(read(error), "${file.name}: data.$key is not a string")
            }
            kinds += error.kind
        }
        assertEquals(ErrorKind.entries.filter { it != ErrorKind.Unknown }.toSet(), kinds, "every error kind has a fixture")
    }

    /**
     * `harnessUnavailable` names the harness and why it cannot be used (protocol.md §1.3), and
     * stays non-definitive: the request is kept and resent once the harness is available.
     */
    @Test
    fun harnessUnavailableCarriesTheHarnessAndTheReason() {
        val message = AasJson.decodeFromJsonElement(RpcMessage.serializer(), read(File(root, "errors/harnessUnavailable.json")))
        val error = assertNotNull(message.error)
        assertEquals(ErrorKind.HarnessUnavailable, error.kind)
        assertEquals(false, error.kind.definitive)
        assertEquals("codex", error.harnessId)
        assertEquals("not logged in", error.reason)
        // An older server sent neither: the accessors say so instead of inventing values.
        val bare = RpcError(ErrorKind.HarnessUnavailable.code, "harness codex is unavailable")
        assertEquals(ErrorKind.HarnessUnavailable, bare.kind)
        assertEquals(null, bare.harnessId)
        assertEquals(null, bare.reason)
    }

    @Test
    fun http() {
        val serializers: Map<String, KSerializer<*>> = mapOf(
            "pair_request" to PairRequest.serializer(),
            "pair_response" to PairResponse.serializer(),
            "blob_upload_response" to BlobUploadResponse.serializer(),
            "http_error" to HttpError.serializer(),
            "health" to Health.serializer(),
        )
        val seen = mutableSetOf<String>()
        for (file in files("http")) {
            val serializer = assertNotNull(serializers[file.nameWithoutExtension], "no serializer for ${file.name}")
            roundTrip(serializer, read(file), file.name)
            seen += file.nameWithoutExtension
        }
        assertEquals(serializers.keys, seen, "every HTTP body has a fixture")
    }

    @Test
    fun fixturesAreAlsoOnTheTestClasspath() {
        assertNotNull(javaClass.classLoader.getResource("protocol/events/item_started.json"))
    }

    companion object {
        private val CATEGORIES = setOf("requests", "responses", "errors", "events", "notifications", "http")

        /** The request fixtures of another shape of a method's params (`requests/<method>_<variant>.json`). */
        private val REQUEST_VARIANTS = setOf("thread_create_workspaceThread.json")

        /** The `data` fields of errors the client reads, with their typed accessors. */
        private val ERROR_DETAILS: Map<String, (RpcError) -> String?> = mapOf(
            RpcError.DATA_HARNESS_ID to { it.harnessId },
            RpcError.DATA_REASON to { it.reason },
            RpcError.DATA_CAPABILITY to { it.capability },
            RpcError.DATA_DETAIL to { it.detail },
            RpcError.DATA_COMMAND to { it.command },
        )

        private val root: File = File(
            System.getProperty("aas.fixtures") ?: error("system property aas.fixtures is not set (run through Gradle)"),
        )
    }
}
