plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.serialization)
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    api(libs.kotlinx.serialization.json)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.junit)
}

// The golden fixtures generated by `cargo test -p aas-protocol` are the wire contract.
val fixturesDir = rootProject.layout.projectDirectory.dir("../fixtures/protocol")

sourceSets {
    test {
        resources.srcDir(fixturesDir.asFile.parentFile)
    }
}

// The recorded shape of each version of the stored models (StoredModelsTest, docs/android.md 15.2).
val storedModelsDir = layout.projectDirectory.dir("stored-models")

tasks.test {
    inputs.dir(fixturesDir).withPropertyName("fixtures")
    systemProperty("aas.fixtures", fixturesDir.asFile.absolutePath)
    inputs.dir(storedModelsDir).withPropertyName("storedModels")
    systemProperty("aas.storedModels", storedModelsDir.asFile.absolutePath)
    // Recording a new version's shape writes into the source tree: run again whenever it is asked.
    inputs.property("updateStoredModels", providers.environmentVariable("AAS_UPDATE_STORED_MODELS").orElse(""))
}
