plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.serialization)
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    api(libs.kotlinx.serialization.json)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.junit)
}

// The golden fixtures generated by `cargo test -p aas-protocol` are the wire contract.
val fixturesDir = rootProject.layout.projectDirectory.dir("../fixtures/protocol")

sourceSets {
    test {
        resources.srcDir(fixturesDir.asFile.parentFile)
    }
}

tasks.test {
    inputs.dir(fixturesDir).withPropertyName("fixtures")
    systemProperty("aas.fixtures", fixturesDir.asFile.absolutePath)
}
